version: '3.9'

services:
  server:
    image: jv112/nct
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10